// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {aliasTextOrSymbol} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: ")xQfQQOOO!oQQO'#DQO!yQQO'#C`O#RQQO'#DPO#YOQO'#CeO#bOPO'#DUOOQO'#Cf'#CfOOQO'#DP'#DPOOQO'#Cn'#CnO#xQQO'#CkO#gQQO'#C}O$]QQO'#C^O$bQQO'#CjO$sQQO'#CiOOQO'#Cm'#CmQfQQOOO%RQQO,59OO%RQQO'#CoO%^QQO,58zOOQO,59P,59POOQO,59p,59pOOQO-E6l-E6lO&UQQO'#C_O&`QQO,59iO&hOPO'#ChO&mQQO,58xOOQO'#Cl'#ClOOQO'#Cr'#CrO'XQQO,59UOOQO'#Cq'#CqO'jQQO,59TOfQQO,59TO(UQQO,59TO'jQQO,59TOOQO,59T,59TOOQO-E6k-E6kOOQO'#DQ'#DQOOQO1G.j1G.jO(dQQO,59ZOOQO,59Z,59ZOOQO-E6m-E6mO#gQQO'#CpO)_QQO1G/TOOQO1G/T1G/TOOQO,59S,59SO)gQQO1G.dOOQO-E6p-E6pOOQO-E6o-E6oO*RQQO1G.oOOQO,59_,59_O*aQQO1G.oOfQQO1G.oOOQO-E6q-E6qO*aQQO1G.oOOQO1G.o1G.oO*{QQO'#CgOOQO,59[,59[OOQO-E6n-E6nOOQO7+$o7+$oO+VQQO7+$ZO+VQQO7+$ZOOQO7+$Z7+$ZO+qQQO7+$ZP#gQQO'#CsO,PQQO<<GuO,PQQO<<GuOOQO<<Gu<<GuO,kQQOAN=a",
  stateData: "-Y~OkOSlOSmOSnOSoOSpOS~OTPOUPOVPOrYOwSOyTO~OTsXUsXVsXrsXwsXysXzsX|sX}sX!OsX{sX~OutXvtX~PzOu`OvaO~OvaO~PzOTcOUcO~OidO~OTPOUPOVPOwSOyTO~Or_Xz_X|_X}_X!O_X~P#gO|hO~OrYOz^X|^X}^X!O^X~OzoO|hO}mO!OrO~OTtOUtOVtO~OvaOTSaUSaVSarSawSaySazSa|Sa}Sa!OSa{Sa~OzRX{RX~P#gOzyO{{O~Oi|O~O}mOTQaUQaVQahQarQawQayQa~OrYOz^a|^a}^a!O^a~O}mOT]aU]aV]ah]ar]aw]ay]a~Oz!TO|hO}mO!O!WO~Ou`OTcaUcaVcarcavcawcaycazca|ca}ca!Oca{ca~OzyO{![O~O}mOTQiUQiVQihQirQiwQiyQi~OrYO|hO}mO!O!_O~O}mOT]iU]iV]ih]ir]iw]iy]i~OzZX{ZX~P#gO}mOT]qU]qV]qh]qr]qw]qy]q~OrYO|hO}mO!O!dO~O}mOT]yU]yV]yh]yr]yw]yy]y~O}mOT]!RU]!RV]!Rh]!Rr]!Rw]!Ry]!R~O}k~",
  goto: "&lyPPz!O!RPPP!_!R!R!n!qz#Q#Z#b#j#p$S$Z$a%O%^PPPPPPPPP%dP%p%|PPP&`T^O_RgYeVOXY_foy!T!X!adROXY_foy!T!X!aRwaR!YyQiZQq]Q!VpQ!^!QR!c!`S]O_V!Ro!T!aZ[O_o!T!a]k[lo!Q!T!`Q_ORs_YXO_o!T!aUeXf!XQfYR!XySbQRRxbQzgR!ZzQn]Q}i[!Pn}!S!]!b!eS!SpqS!]!Q!VS!b!^!`R!e!cQl[U!Ol!Q!`Q!QoR!`!TQp]R!UpSZO_]j[lo!Q!T!`eWOXY_foy!T!X!adQOXY_foy!T!X!aQu`RvaeUOXY_foy!T!X!a",
  nodeNames: "⚠ Document Transform Operation Range Symbol Text Placeholder Span Tag Alias Operation Alias Block Reference Select Transform",
  maxTerm: 46,
  skippedNodes: [0],
  repeatNodeCount: 7,
  tokenData: ")`~RgXY!jYZ!u]^#_pq!jrs#wst%ovw%|wx&Rxy't|}'y}!O(O!O!P(T!P!Q(Y!Q![(_![!](p!a!b(u!c!}(_!}#O(z#O#P)P#P#Q)U#R#S(_#T#o(_~~)Z~!oQl~XY!jpq!j~!zQk~YZ#Q]^#V~#VO}~~#[P}~YZ#Q~#dQk~YZ#j]^#V~#qQ}~k~YZ#Q]^#V~#|WU~OY#wZr#wrs$fs#O#w#O#P$k#P;'S#w;'S;=`%i<%lO#w~$kOU~~$nRO;'S#w;'S;=`$w;=`O#w~$|XU~OY#wZr#wrs$fs#O#w#O#P$k#P;'S#w;'S;=`%i;=`<%l#w<%lO#w~%lP;=`<%l#w~%tPw~xy%w~%|Oy~~&ROz~~&WWU~OY&RZw&Rwx$fx#O&R#O#P&p#P;'S&R;'S;=`'n<%lO&R~&sRO;'S&R;'S;=`&|;=`O&R~'RXU~OY&RZw&Rwx$fx#O&R#O#P&p#P;'S&R;'S;=`'n;=`<%l&R<%lO&R~'qP;=`<%l&R~'yO|~~(OOv~~(TOu~~(YOn~~(_Oo~~(dST~!Q![(_!c!}(_#R#S(_#T#o(_~(uOm~~(zOV~~)POr~~)UOp~~)ZO{~~)`O!O~",
  tokenizers: [aliasTextOrSymbol, 0],
  topRules: {"Document":[0,1]},
  tokenPrec: 559
})
