// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {aliasTextOrSymbol} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "*UQfQQOOO!oQQO'#DQO!yQQO'#CaO#RQQO'#DPO#YOQO'#CfO#bOPO'#DUOOQO'#Cg'#CgOOQO'#DP'#DPOOQO'#Co'#CoO#xQQO'#ClO#gQQO'#C}O$]QQO'#C_O$bQQO'#CkO$sQQO'#CjOOQO'#Cn'#CnQfQQOOO%RQQO,59PO%RQQO'#CpO%^QQO,58{OOQO,59Q,59QO&UOQO,59pOOQO-E6m-E6mO&ZQQO'#C`O&eQQO,59iO&mOPO'#CiO&rQQO,58yOOQO'#Cm'#CmOOQO'#Cs'#CsO'^QQO,59VOOQO'#Cr'#CrO'oQQO,59UOfQQO,59UO(ZQQO,59UO'oQQO,59UOOQO,59U,59UOOQO-E6l-E6lOOQO'#DQ'#DQOOQO1G.k1G.kO(iQQO,59[OOQO,59[,59[OOQO-E6n-E6nOOQO1G/[1G/[O#gQQO'#CqO)dQQO1G/TOOQO1G/T1G/TO)lOQO,59TO)qQQO1G.eOOQO-E6q-E6qOOQO-E6p-E6pO*]QQO1G.pOOQO,59`,59`O*kQQO1G.pOfQQO1G.pOOQO-E6r-E6rO*kQQO1G.pOOQO1G.p1G.pO+VQQO'#ChOOQO,59],59]OOQO-E6o-E6oOOQO7+$o7+$oOOQO1G.o1G.oO+aQQO7+$[O+aQQO7+$[OOQO7+$[7+$[O+{QQO7+$[P#gQQO'#CtO,ZQQO<<GvO,ZQQO<<GvOOQO<<Gv<<GvO,uQQOAN=b",
  stateData: "-d~OkOSlOSmOSnOSoOSpOS~OUPOVPOWPOrYOwSOyTO~OUsXVsXWsXrsXwsXysX{sX}sX!OsX!PsX|sX~OutXvtX~PzOu`OvaO~OvaO~PzOUcOVcO~OPdO~OUPOVPOWPOwSOyTO~Or`X{`X}`X!O`X!P`X~P#gO}hO~OrYO{_X}_X!O_X!P_X~O{oO}hO!OmO!PrO~OUtOVtOWtO~OvaOUTaVTaWTarTawTayTa{Ta}Ta!OTa!PTa|Ta~OzyO~O{SX|SX~P#gO{zO||O~OP}O~O!OmOURaVRaWRaiRarRawRayRa~OrYO{_a}_a!O_a!P_a~O!OmOU^aV^aW^ai^ar^aw^ay^a~O{!UO}hO!OmO!P!XO~Ou`OUdaVdaWdardavdawdayda{da}da!Oda!Pda|da~O{zO|!]O~Oz!^O~O!OmOURiVRiWRiiRirRiwRiyRi~OrYO}hO!OmO!P!aO~O!OmOU^iV^iW^ii^ir^iw^iy^i~O{[X|[X~P#gO!OmOU^qV^qW^qi^qr^qw^qy^q~OrYO}hO!OmO!P!fO~O!OmOU^yV^yW^yi^yr^yw^yy^y~O!OmOU^!RV^!RW^!Ri^!Rr^!Rw^!Ry^!R~O!Ok~",
  goto: "&lyPPPz!O!RPPP!_!R!R!n!qz#Q#Z#b#j#p$S$Z$a%O%^PPPPPPPP%dP%p%|PPP&`T^O_RgYeVOXY_foz!U!Y!cdROXY_foz!U!Y!cRwaR!ZzQiZQq]Q!WpQ!`!RR!e!bS]O_V!So!U!cZ[O_o!U!c]k[lo!R!U!bQ_ORs_YXO_o!U!cUeXf!YQfYR!YzSbQRRxbQ{gR![{Qn]Q!Oi[!Qn!O!T!_!d!gS!TpqS!_!R!WS!d!`!bR!g!eQl[U!Pl!R!bQ!RoR!b!UQp]R!VpSZO_]j[lo!R!U!beWOXY_foz!U!Y!cdQOXY_foz!U!Y!cQu`RvaeUOXY_foz!U!Y!c",
  nodeNames: "⚠ TextOrSymbol Document Transform Operation Range Symbol Text Placeholder Span Tag Alias Operation Alias Block Reference Select Transform",
  maxTerm: 47,
  skippedNodes: [0],
  repeatNodeCount: 7,
  tokenData: ")h~RhXY!mYZ!x]^#bpq!mrs#zst%rvw&Pwx&Uxy'wyz'||}(R}!O(W!O!P(]!P!Q(b!Q![(g![!](x!a!b(}!c!}(g!}#O)S#O#P)X#P#Q)^#R#S(g#T#o(g~~)c~!rQl~XY!mpq!m~!}Qk~YZ#T]^#Y~#YO!O~~#_P!O~YZ#T~#gQk~YZ#m]^#Y~#tQ!O~k~YZ#T]^#Y~$PWV~OY#zZr#zrs$is#O#z#O#P$n#P;'S#z;'S;=`%l<%lO#z~$nOV~~$qRO;'S#z;'S;=`$z;=`O#z~%PXV~OY#zZr#zrs$is#O#z#O#P$n#P;'S#z;'S;=`%l;=`<%l#z<%lO#z~%oP;=`<%l#z~%wPw~xy%z~&POy~~&UO{~~&ZWV~OY&UZw&Uwx$ix#O&U#O#P&s#P;'S&U;'S;=`'q<%lO&U~&vRO;'S&U;'S;=`'P;=`O&U~'UXV~OY&UZw&Uwx$ix#O&U#O#P&s#P;'S&U;'S;=`'q;=`<%l&U<%lO&U~'tP;=`<%l&U~'|O}~~(ROz~~(WOv~~(]Ou~~(bOn~~(gOo~~(lSU~!Q![(g!c!}(g#R#S(g#T#o(g~(}Om~~)SOW~~)XOr~~)^Op~~)cO|~~)hO!P~",
  tokenizers: [aliasTextOrSymbol, 0],
  topRules: {"Document":[0,2]},
  tokenPrec: 569
})
