// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  TextOrSymbol = 1,
  Document = 2,
  Transform = 3,
  Range = 5,
  Symbol = 6,
  Text = 7,
  Placeholder = 8,
  Span = 9,
  Tag = 10,
  Alias = 13,
  Block = 14,
  Reference = 15
