// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  aliasTextOrSymbol = 25,
  Document = 1,
  Transform = 2,
  Range = 4,
  Symbol = 5,
  Text = 6,
  Placeholder = 7,
  Span = 8,
  Tag = 9,
  Alias = 12,
  Block = 13,
  Reference = 14
